var document; /*宣言されていない変数やオブジェクトがあるとエラーが出てくるが、documentは宣言せずともどこにでも使える記述*/
document.write("Hello World");
document.write("私の名前は田中です。<br>");
document.write("年齢は25歳です。");
document.write("あいうえお<br>");
document.write("かきくけこ<br>");
document.write("さしすせそ<br>");
document.write("月曜日<br>火曜日<br>水曜日");
document.write("<h1>あいうえお</h1>");
document.write("<p>かきくけこ</p>");
document.write("さしすせそ");
alert("別のページに移動します。");
confirm("別のページに移動してもいいですか？");
alert("このページを離れようとしています。");
confirm("ログアウトしますか？");
document.write(20170813);
document.write("<br>");
document.write(10.5);
document.write("<br>");
document.write(20.3);
document.write("<br>");
document.write(-100);
document.write("<br>");
document.write(53+10);
document.write("<br>");
document.write("Hello World"); document.write("Good!");
document.write("<br>");
document.write("090-1111-2222"); document.write("電話番号");
document.write("<br>");
var a ="山本"; document.write(a);
document.write("<br>");
var number = 208; document.write(number);
document.write("<br>");
var tell="090-0000-1234"; 
document.write(tell);
document.write("<br>");
var month=12;
document.write(month+"月");
document.write("<br>");
var day=25;
document.write(day+"日");
document.write("<br>");
document.write(3*3);
document.write(4/2);
document.write("<br>");
var a=5+10;
document.write(a);
document.write("<br>");
var e="2+3";
var f="4-1";
document.write(e); document.write("<br>");
document.write(f);
document.write("<br>");
var g=5*5;
var h="5*5";
document.write(h+"="+g);
document.write("<br>");
var abc1=10%3;
document.write(abc1);
document.write("<br>");
var abc2=5%2;
document.write("5÷2の余りは"+abc2);
document.write("<br>");
var a1=3;
document.write(++a1);
document.write("<br>");
var a2=20;
document.write(++a2);
document.write("<br>");
var a3=10;
document.write(++a3);
document.write("<br>");
document.write(++a3);
document.write("<br>");
var a4=5;
document.write(a4++);
document.write("<br>");
document.write(a4++);
document.write("<br>");
document.write(a4++);
document.write("<br>");
var a5=15;
document.write(--a5); document.write(--a5); document.write(--a5);
document.write("<br>");
var a8=2;
document.write(++a8);
document.write(a8++);
document.write("<br>");
document.write(a8);
document.write("<br>");
var b=5;
document.write(++b); document.write(b); document.write(b);
document.write("<br>");
var aa=10;
document.write(aa--);
document.write(aa--);
document.write(aa--);
document.write(aa);
document.write(aa);
document.write("<br>");

document.write("<br>");

